### ISSUE TITLE
rank not updating

### ISSUE THREAD

**Issue by esheldon** [pmelchior/des-exp-checker#82]
The rank stays fixed in the upper right, but is updated when I click explicitly on the leader board

**Comment by pmelchior** [comment]
The rank gets updated automatically every 5 minutes, or whenever you load the leaderboard. A bit inconsistent, but the purpose of the automatic update is to show when your rank has changed (so that you get cracking again).

I think that's OK.

**Comment by esheldon** [comment]
It did not update for me when I viewed the leader board

Using firefox 41.02

**Comment by pmelchior** [comment]
Your rank badge and the leaderboard showed different numbers?

**Comment by esheldon** [comment]
Yes, in the upper left it showed 11 before and after checking the
leader board, which said 7

**Comment by pmelchior** [comment]
Confirmed. Seems the opening of the leaderboard doesn't trigger the rank update.
